server:
  port: 3344
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
# github 的文件地址
          uri: https://github.com/LoongZhangKlein/microservicecloud-config.git